/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

/**
 *
 * @author manik
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCart = new javax.swing.JPanel();
        pnlChartTitle = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlContainer = new javax.swing.JPanel();
        pnlMainTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlCart.setPreferredSize(new java.awt.Dimension(400, 400));
        pnlCart.setLayout(new java.awt.BorderLayout());

        pnlChartTitle.setPreferredSize(new java.awt.Dimension(400, 80));
        pnlChartTitle.setRequestFocusEnabled(false);
        pnlChartTitle.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Cart");
        pnlChartTitle.add(jLabel2);

        pnlCart.add(pnlChartTitle, java.awt.BorderLayout.NORTH);

        add(pnlCart, java.awt.BorderLayout.EAST);

        pnlContainer.setLayout(new java.awt.BorderLayout());

        pnlMainTitle.setPreferredSize(new java.awt.Dimension(686, 80));
        pnlMainTitle.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        pnlMainTitle.add(jLabel1);

        pnlContainer.add(pnlMainTitle, java.awt.BorderLayout.PAGE_START);

        add(pnlContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlChartTitle;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlMainTitle;
    // End of variables declaration//GEN-END:variables
}
