/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pallets;

import entities.CartItemEntity;

/**
 *
 * @author manik
 */
public class CartItem extends javax.swing.JPanel {

    CartItemEntity cartItem;

    /**
     * Creates new form CartItem
     */
    public CartItem(CartItemEntity cartItem) {
        initComponents();
        this.cartItem = cartItem;

        lblProductName.setText(this.cartItem.getProductsEntity().getName());
        lblQty.setText(String.valueOf(this.cartItem.getQuantity()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductName = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductName.setText("Nama Product");
        add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblQty.setText("Quantity");
        add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblQty;
    // End of variables declaration//GEN-END:variables
}
