/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import entities.CartEntity;
import entities.ProductsEntity;
import java.awt.BorderLayout;
import java.util.ArrayList;
import models.CartModel;
import models.ProductsModel;
import pallets.CardProduct;
import pallets.CartMenu;
import raven.swing.AvatarIcon;

/**
 *
 * @author manik
 */
public class Dashboard extends javax.swing.JPanel {

    ArrayList<ProductsEntity> products;
    CartModel cartModel;


    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        init();

    }

    private void init() {

        cartModel = CartModel.getInstance();

        products = ProductsModel.getProducts();

        scrollPane.getVerticalScrollBar().setUnitIncrement(5);

        CartMenu cartMenu = new CartMenu(cartModel);

        pnlCart.add(cartMenu);

        cartMenu.setVisible(true);


        for (ProductsEntity product : products) {
            renderProduct(product);

        }
        for (ProductsEntity product : products) {
            renderProduct(product);
        }
    }


    private void renderProduct(ProductsEntity product) {
        CardProduct cardProduct = new CardProduct(product, cartModel);
        pnlItem.add(cardProduct);
        cardProduct.setVisible(true);
        scrollPane.repaint();
        scrollPane.revalidate();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCart = new javax.swing.JPanel();
        pnlContainer = new javax.swing.JPanel();
        pnlMainTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        pnlItem = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(5, 0));

        pnlCart.setPreferredSize(new java.awt.Dimension(400, 400));
        pnlCart.setLayout(new java.awt.GridLayout(1, 1));
        add(pnlCart, java.awt.BorderLayout.EAST);

        pnlContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 5));
        pnlContainer.setLayout(new java.awt.BorderLayout());

        pnlMainTitle.setPreferredSize(new java.awt.Dimension(686, 80));
        pnlMainTitle.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        pnlMainTitle.add(jLabel1);

        pnlContainer.add(pnlMainTitle, java.awt.BorderLayout.PAGE_START);

        pnlMain.setLayout(new java.awt.BorderLayout(0, 5));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Products");
        jLabel6.setAutoscrolls(true);
        pnlMain.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        pnlItem.setLayout(new java.awt.GridLayout(8, 3, 10, 10));
        scrollPane.setViewportView(pnlItem);

        pnlMain.add(scrollPane, java.awt.BorderLayout.CENTER);

        pnlContainer.add(pnlMain, java.awt.BorderLayout.CENTER);

        add(pnlContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlCart;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlItem;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMainTitle;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
